#!/bin/bash

command_exists() {
    command -v "$1" &>/dev/null
}

if ! command_exists git; then
    if command_exists apt-get; then
        sudo apt-get update
        sudo apt-get install -y git
    elif command_exists brew; then
        brew install git
    else
        echo "Please install git first"
        exit 1
    fi
fi

git clone https://github.com/harryzcy/dotfiles.git $HOME/dotfiles

bash $HOME/dotfiles/script/setup.sh
