#!/bin/bash

if ! command -v git &>/dev/null; then
    echo "git is not installed"
    exit 1
fi

git clone https://github.com/harryzcy/dotfiles.git $HOME/dotfiles

bash $HOME/dotfiles/script/setup.sh
