name: Dotfiles Test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  detect-files:
    name: Detect Changed Files
    runs-on: ubuntu-latest
    outputs:
      macos_any_changed: ${{ steps.changed-files.outputs.macos_any_changed }}
      linux_any_changed: ${{ steps.changed-files.outputs.linux_any_changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            macos:
              - '**'
              - '!linux'
              - '!script/**/**_linux.sh'
            linux:
              - '**'
              - '!macos'
              - '!script/**/**_macos.sh'

      - name: Print outputs
        run: |
          echo "macos_any_changed: ${{ steps.changed-files.outputs.macos_any_changed }}"
          echo "linux_any_changed: ${{ steps.changed-files.outputs.linux_any_changed }}"

  setup:
    name: Test Setup
    needs: detect-files
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest]

    steps:
      - name: Clean up installed software on macOS
        if: startsWith(matrix.os, 'macos') && needs.detect-files.outputs.macos_any_changed == 'true'
        run: |
          brew uninstall --ignore-dependencies --force $(brew list --formula)
          brew uninstall --cask --force $(brew list --cask)
          brew cleanup --prune-prefix
          sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
          rm -rf /Users/runner/.gitconfig /Users/runner/.gitignore_global

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install using Makefile on macOS
        if: startsWith(matrix.os, 'macos') && needs.detect-files.outputs.macos_any_changed == 'true'
        run: make setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests on macOS
        if: startsWith(matrix.os, 'macos') && needs.detect-files.outputs.macos_any_changed == 'true'
        run: |
          source ~/.zshrc
          make test
        shell: zsh {0}

      - name: Install using Makefile on Linux
        if: startsWith(matrix.os, 'ubuntu') && needs.detect-files.outputs.linux_any_changed == 'true'
        run: make setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests on Linux
        if: startsWith(matrix.os, 'ubuntu') && needs.detect-files.outputs.linux_any_changed == 'true'
        run: |
          source ~/.zshrc
          make test
        shell: zsh {0}
