name: Dotfiles Test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest]

    steps:
      - name: Clean up installed software on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew uninstall --ignore-dependencies --force $(brew list --formula)
          brew uninstall --cask --force $(brew list --cask)
          brew cleanup --prune-prefix
          sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
          rm -rf /Users/runner/.gitconfig /Users/runner/.gitignore_global

      - uses: actions/checkout@v4

      - name: Install using Makefile
        run: |
          make setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          source ~/.zshrc
          make test
        shell: zsh {0}

      - name: Run upgrade command
        run: |
          make upgrade
        shell: zsh {0}

      - name: Run clean command
        run: |
          make clean
        shell: zsh {0}
