name: Lint

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@93e63bd27d176cac11d24d609c8b7fdab38f32ba # main

  go-lint:
    name: Go Lint
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@93e63bd27d176cac11d24d609c8b7fdab38f32ba # main
    with:
      working-directory: dotd
