name: Lint

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@36677a66188f3c7ff6d186727ba1413c53424e4e # main

  shell-lint:
    name: Shell Lint
    uses: harryzcy/github-actions/.github/workflows/shell-lint.yml@36677a66188f3c7ff6d186727ba1413c53424e4e # main

  go-lint:
    name: Go Lint
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@36677a66188f3c7ff6d186727ba1413c53424e4e # main
    with:
      working-directory: dotd
