name: Lint

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@2d3c3315851099b16dcf3d6488dc56c164b0760e # main

  shell-lint:
    name: Shell Lint
    uses: harryzcy/github-actions/.github/workflows/shell-lint.yml@2d3c3315851099b16dcf3d6488dc56c164b0760e # main

  go-lint:
    name: Go Lint
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@2d3c3315851099b16dcf3d6488dc56c164b0760e # main
    with:
      working-directory: dotd
